/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.EntregaPendiente;
import dao.EntregasDAO;
import dao.EntregasDAOImpl;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jcarlos.porcel
 */
public class FormEntregasPendientes extends javax.swing.JFrame {

    private DatabaseUtils databaseUtils;
    private Connection connectionDB, connectionTemp;
    private DefaultTableModel dtm;    
    private int idTipoTransaccionEntrega;  // tipo de entrega q se ejecutara
    private byte idLugar;
    private byte idTerminal;
    private String usuario;
    private DecimalFormat df;
    
    EntregasDAO entregasDAO;

    public FormEntregasPendientes(Connection connectionDB, 
            int idTipoTransaccionEntrega, byte idLugar, 
            byte idTerminal, String usuario) {        
        initComponents();
        
        this.connectionDB = connectionDB;        
        this.idTipoTransaccionEntrega = idTipoTransaccionEntrega;
        this.idLugar = idLugar;
        this.idTerminal = idTerminal;
        this.usuario = usuario;
        
        headerTabla();
        iniciarVariables();
        llenarPendientesEntrega();
    }
    
    public void headerTabla() {
        Font f = new Font("Times New Roman", Font.BOLD, 13);

        jtPendientes.getTableHeader().setFont(f);
        jtPendientes.getTableHeader().setBackground(Color.orange);
        
        jtProductosPendientes.getTableHeader().setFont(f);
        jtProductosPendientes.getTableHeader().setBackground(Color.orange);
    }
    
    private void iniciarVariables(){
        entregasDAO = new EntregasDAOImpl(connectionDB);
    }
    
    public void llenarPendientesEntrega(){
        
        ArrayList<EntregaPendiente> lista = new ArrayList<EntregaPendiente>();
        
        lista = entregasDAO.getListaEntregasPendientes();
        
        dtm = (DefaultTableModel) this.jtPendientes.getModel();
        dtm.setRowCount(0);
        
        jtPendientes.setModel(dtm);
        
        Object[] fila = new Object[6];
        
        for(int i=0; i< lista.size(); i++){
            fila[0] = lista.get(i).getIdTransaccionCredito();
            fila[1] = lista.get(i).getNroTipoTransaccion();
            fila[2] = lista.get(i).getFecha();
            fila[3] = lista.get(i).getNombreCompleto();
            fila[4] = lista.get(i).getDireccion();
            fila[5] = lista.get(i).getTelefonos();
            
            dtm.addRow(fila);
        }
        jtPendientes.setModel(dtm);
    }
    
    public void llenarProductosPendientes(int idTransaccion){
        ArrayList<EntregaPendiente> lista = new ArrayList<EntregaPendiente>();
        
        lista = entregasDAO.getProductosPendientes(idTransaccion);
        
        dtm = (DefaultTableModel) this.jtPorEntregar.getModel();
        dtm.setRowCount(0);
        
        jtProductosPendientes.setModel(dtm);
        
        Object[] fila = new Object[8];
        
        for(int i=0; i< lista.size(); i++){
            fila[0] = lista.get(i).getIdTransaccionCredito();
            fila[1] = lista.get(i).getIdProducto();
            fila[2] = lista.get(i).getIdUnidadMedida();
            fila[3] = lista.get(i).getNombreProducto();
            fila[4] = lista.get(i).getNombreUnidadMedida();
            fila[5] = lista.get(i).getCantidadCredido();
            fila[6] = lista.get(i).getCantidadEntrega();
            fila[7] = lista.get(i).getDiferencia();
            
            dtm.addRow(fila);
        }        
        jtProductosPendientes.setModel(dtm);
    }
    
    public void seleccionarPendiente(){
        
        int filSel = jtPendientes.getSelectedRow();
        int idTransaccion = (int) jtPendientes.getValueAt(filSel, 0);
        
        llenarProductosPendientes(idTransaccion);
        
    }

    
    
    public FormEntregasPendientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPendientes = new javax.swing.JTable();
        jlTituloFormulario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPorEntregar = new javax.swing.JTable();
        jlTituloFormulario1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbPorEntregar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProductosPendientes = new javax.swing.JTable();
        jlTituloFormulario2 = new javax.swing.JLabel();
        jbTransaccion = new javax.swing.JButton();
        jbSalir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idTransaccion", "Nro Trans.", "Fecha", "Nombre Cliente", "Direccion", "Telefonos"
            }
        ));
        jtPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPendientesMouseClicked(evt);
            }
        });
        jtPendientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPendientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtPendientes);
        if (jtPendientes.getColumnModel().getColumnCount() > 0) {
            jtPendientes.getColumnModel().getColumn(0).setMinWidth(0);
            jtPendientes.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtPendientes.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jlTituloFormulario.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloFormulario.setText("Productos Pendientes");

        jtPorEntregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idTransaccion", "idProducto", "idUnidadMedida", "Nombre Producto", "Unidad Medida", "A Entregar"
            }
        ));
        jScrollPane2.setViewportView(jtPorEntregar);
        if (jtPorEntregar.getColumnModel().getColumnCount() > 0) {
            jtPorEntregar.getColumnModel().getColumn(0).setMinWidth(0);
            jtPorEntregar.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtPorEntregar.getColumnModel().getColumn(0).setMaxWidth(0);
            jtPorEntregar.getColumnModel().getColumn(1).setMinWidth(0);
            jtPorEntregar.getColumnModel().getColumn(1).setPreferredWidth(0);
            jtPorEntregar.getColumnModel().getColumn(1).setMaxWidth(0);
            jtPorEntregar.getColumnModel().getColumn(2).setMinWidth(0);
            jtPorEntregar.getColumnModel().getColumn(2).setPreferredWidth(0);
            jtPorEntregar.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jlTituloFormulario1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario1.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloFormulario1.setText("Entregas Pendientes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("A Entregar");

        jbPorEntregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jtProductosPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idTransaccion", "idProducto", "idUnidadMedida", "Nombre Producto", "Unidad Medida", "Cantidad", "Entregado", "Diferencia"
            }
        ));
        jScrollPane3.setViewportView(jtProductosPendientes);
        if (jtProductosPendientes.getColumnModel().getColumnCount() > 0) {
            jtProductosPendientes.getColumnModel().getColumn(0).setMinWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(0).setMaxWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(1).setMinWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(1).setPreferredWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(1).setMaxWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(2).setMinWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(2).setPreferredWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(2).setMaxWidth(0);
            jtProductosPendientes.getColumnModel().getColumn(6).setHeaderValue("Entregado");
            jtProductosPendientes.getColumnModel().getColumn(7).setHeaderValue("Diferencia");
        }

        jlTituloFormulario2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario2.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloFormulario2.setText("Por Entregar");

        jbTransaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configurar.png"))); // NOI18N
        jbTransaccion.setText("Transaccion");
        jbTransaccion.setAlignmentY(0.7F);
        jbTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransaccionActionPerformed(evt);
            }
        });

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_window.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlTituloFormulario2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad)
                            .addComponent(jbPorEntregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbTransaccion)
                                .addGap(236, 236, 236)
                                .addComponent(jbSalir))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jlTituloFormulario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTituloFormulario)
                    .addComponent(jlTituloFormulario2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPorEntregar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbTransaccion))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jlTituloFormulario1)
                    .addContainerGap(606, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPendientesMouseClicked
        seleccionarPendiente();
    }//GEN-LAST:event_jtPendientesMouseClicked

    private void jtPendientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPendientesKeyPressed
        seleccionarPendiente();
    }//GEN-LAST:event_jtPendientesKeyPressed

    private void jbTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransaccionActionPerformed
        jbTransaccion.setEnabled(false);


        jbTransaccion.setEnabled(true);
    }//GEN-LAST:event_jbTransaccionActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEntregasPendientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbPorEntregar;
    private javax.swing.JToggleButton jbSalir;
    private javax.swing.JButton jbTransaccion;
    private javax.swing.JLabel jlTituloFormulario;
    private javax.swing.JLabel jlTituloFormulario1;
    private javax.swing.JLabel jlTituloFormulario2;
    private javax.swing.JTable jtPendientes;
    private javax.swing.JTable jtPorEntregar;
    private javax.swing.JTable jtProductosPendientes;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
