/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.StockProducto;
import almacenes.model.StockVencimiento;
import dao.LugarDAO;
import dao.LugarDAOImpl;
import dao.ProductoDAOImpl;
import dao.reportes.ReporteVentasDAO;
import dao.reportes.ReporteVentasDAOImpl;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jcapax
 */
public class FormStockProducto extends javax.swing.JFrame {

    private DatabaseUtils databaseUtils;
    private Connection connectionDB;
    DefaultTableModel dtm;
    byte idLugar;
    ProductoDAOImpl productoDAOImpl;
    
    public FormStockProducto() {
        initComponents();
    }
        
    public FormStockProducto(Connection connectionDB) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.databaseUtils = new DatabaseUtils();
        this.connectionDB = connectionDB;
        this.idLugar = idLugar;
        headerTabla();
        llenarComboLugar();
        llenarTablaStockProducto("");
    }
    
    public void llenarComboLugar(){
        
        String sel = "Sel";
        jlIdLugar.setText("0");
        jcLugar.removeAllItems();
        jcLugar.addItem(sel);
        
        LugarDAO lugarDAOImpl = new LugarDAOImpl(connectionDB);
        
        HashMap<String, Integer> map = lugarDAOImpl.lugarClaveValor();

        for (String s : map.keySet()) {
            jcLugar.addItem(s.toString());
        }
        jlIdLugar.setVisible(false);
        llenarTablaStockProducto("");
    }
    
    private void seleccionarElementoLugar() {
        String sel = null;
        
        String comp = "Sel";
        
        LugarDAO lugarDAOImpl = new LugarDAOImpl(connectionDB);
        
        HashMap<String, Integer> map = lugarDAOImpl.lugarClaveValor();
            
        try {
            sel = jcLugar.getSelectedItem().toString();
            if(sel.equals(comp)){
                jlIdLugar.setText("0");
            }
            else{
                jlIdLugar.setText(map.get(sel).toString());
            }
        } catch (Exception e) {
        }
        idLugar = Byte.valueOf(jlIdLugar.getText());
        llenarTablaStockProducto("");
        
    }
    
    public void headerTabla(){
        Font f = new Font("Times New Roman", Font.BOLD, 14);
        
        jtStockProducto.getTableHeader().setFont(f);
        jtStockProducto.getTableHeader().setBackground(Color.orange);
        
        jtStockVencimiento.getTableHeader().setFont(f);
        jtStockVencimiento.getTableHeader().setBackground(Color.orange);
    }

    public void llenarTablaStockProducto(String criterio){
         productoDAOImpl = new ProductoDAOImpl(connectionDB);

        ArrayList<StockProducto> r = new ArrayList<StockProducto>();

        r = productoDAOImpl.getListaStockProducto(idLugar, criterio);

        dtm = (DefaultTableModel) this.jtStockProducto.getModel();
        dtm.setRowCount(0);

        jtStockProducto.setModel(dtm);

        Object[] fila = new Object[6];

        for(int i=0; i< r.size(); i++){
            fila[0] = i + 1;
            fila[1] = r.get(i).getNombreProducto();
            fila[2] = r.get(i).getNombreUnidadMedida();
            fila[3] = r.get(i).getStock();
            fila[4] = r.get(i).getIdProducto();
            fila[5] = r.get(i).getIdUnidadMedida();

            dtm.addRow(fila);
        }
        jtStockProducto.setModel(dtm);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtStockProducto = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtxCriterio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcLugar = new javax.swing.JComboBox<>();
        jlIdLugar = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtStockVencimiento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtStockProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "Producto", "Unidad Med.", "Stock", "idProducto", "idUnidadMedida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtStockProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtStockProductoMouseClicked(evt);
            }
        });
        jtStockProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtStockProductoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtStockProductoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtStockProducto);
        if (jtStockProducto.getColumnModel().getColumnCount() > 0) {
            jtStockProducto.getColumnModel().getColumn(0).setMinWidth(40);
            jtStockProducto.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtStockProducto.getColumnModel().getColumn(0).setMaxWidth(40);
            jtStockProducto.getColumnModel().getColumn(1).setMinWidth(300);
            jtStockProducto.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtStockProducto.getColumnModel().getColumn(1).setMaxWidth(300);
            jtStockProducto.getColumnModel().getColumn(3).setResizable(false);
            jtStockProducto.getColumnModel().getColumn(4).setMinWidth(0);
            jtStockProducto.getColumnModel().getColumn(4).setPreferredWidth(0);
            jtStockProducto.getColumnModel().getColumn(4).setMaxWidth(0);
            jtStockProducto.getColumnModel().getColumn(5).setResizable(false);
            jtStockProducto.getColumnModel().getColumn(5).setMinWidth(0);
            jtStockProducto.getColumnModel().getColumn(5).setPreferredWidth(0);
            jtStockProducto.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_window.png"))); // NOI18N
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STOCK DE PRODUCTOS");

        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Criterio de Busqueda");

        jtxtxCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtxCriterioActionPerformed(evt);
            }
        });
        jtxtxCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtxCriterioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtxCriterioKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Lugar");

        jcLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcLugarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jtStockVencimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha Vencimiento", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtStockVencimiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnImprimir)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxtxCriterio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlIdLugar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalir)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlIdLugar)
                        .addGap(540, 540, 540))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jcLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnImprimir)
                                .addGap(3, 3, 3)))
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jtxtxCriterioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtxCriterioKeyPressed

    }//GEN-LAST:event_jtxtxCriterioKeyPressed

    private void jtxtxCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtxCriterioKeyReleased
        String criterio = "";
        if (jtxtxCriterio.getText().length() != 0) {

            criterio = jtxtxCriterio.getText();
        } else {
            criterio = "";
        }
        llenarTablaStockProducto(criterio);

    }//GEN-LAST:event_jtxtxCriterioKeyReleased

    private void jcLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcLugarActionPerformed
        seleccionarElementoLugar();
    }//GEN-LAST:event_jcLugarActionPerformed

    private void jtxtxCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtxCriterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtxCriterioActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        imprimir(Integer.valueOf(jlIdLugar.getText()));
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jtStockProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtStockProductoKeyReleased
        seleccionarProducto();
    }//GEN-LAST:event_jtStockProductoKeyReleased

    private void jtStockProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtStockProductoMouseClicked
        seleccionarProducto();
    }//GEN-LAST:event_jtStockProductoMouseClicked

    private void jtStockProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtStockProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtStockProductoKeyTyped

    public void imprimir(int idLugar){
        ReporteVentasDAO reporte = new ReporteVentasDAOImpl(connectionDB, "0");
        reporte.stockProductosLugar(idLugar);
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStockProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStockProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStockProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStockProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStockProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcLugar;
    private javax.swing.JLabel jlIdLugar;
    private javax.swing.JTable jtStockProducto;
    private javax.swing.JTable jtStockVencimiento;
    private javax.swing.JTextField jtxtxCriterio;
    // End of variables declaration//GEN-END:variables

    private void seleccionarProducto() {
        
        int fila = jtStockProducto.getSelectedRow();
        
        int idProducto = (int) jtStockProducto.getValueAt(fila, 4);
        byte idUnidadMedida = (byte) jtStockProducto.getValueAt(fila, 5);
        
        //llenarStockVencimiento(idProducto, idUnidadMedida);
        
    }

    private void llenarStockVencimiento(int idProducto, byte idUnidadMedida) {
        ArrayList<StockVencimiento> list = new ArrayList<>();
        
        list = productoDAOImpl.getListStockVencimiento(idLugar, idProducto, idUnidadMedida);
        
        dtm = (DefaultTableModel) this.jtStockVencimiento.getModel();
        dtm.setRowCount(0);

        jtStockVencimiento.setModel(dtm);

        Object[] fila = new Object[2];

        for (int i = 0; i < list.size(); i++) {
            fila[0] = list.get(i).getFechaVencimiento();
            fila[1] = list.get(i).getCantidad();
            
            dtm.addRow(fila);
        }
        

        TableColumnModel columnModel = jtStockVencimiento.getColumnModel();
        
        TableColumn cantidadStock = columnModel.getColumn(1);
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(jLabel1.RIGHT);
        
        cantidadStock.setCellRenderer(renderer);
        
        jtStockVencimiento.setModel(dtm);
    }
}
