/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.DetalleTransaccion;
import almacenes.model.Transaccion;
import dao.DetalleTransaccionDAO;
import dao.DetalleTransaccionDAOImpl;
import dao.ProductoDAO;
import dao.ProductoDAOImpl;
import dao.TransaccionDAO;
import dao.TransaccionDAOImpl;
import dao.UnidadMedidaDAO;
import dao.UnidadMedidaDAOImpl;
import dao.UnidadProductoDAO;
import dao.UnidadProductoDAOImlp;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author jcapax
 */
public class FormDesempaque extends javax.swing.JFrame {

    /**
     * Creates new form FormDesempaque
     */   
    private DatabaseUtils databaseUtils;
    private Connection connectionDB;
    private byte idLugar;
    private byte idTerminal;
    private String usuario;
    private int idProducto, idUnidadMedida1, idUnidadMedida2;
    
    private UnidadProductoDAO unidadProductoDAO;
    private UnidadMedidaDAO unidadMedidaDAO;
    private ProductoDAO productoDAO;
    private TransaccionDAO transaccionDAO;
    private DetalleTransaccionDAO detalleTransaccionDAO;
    
    public FormDesempaque() {
        initComponents();
    }

    public FormDesempaque(Connection connectionDB, String usuario, byte idLugar, byte idTerminal) {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.connectionDB = connectionDB;
        this.usuario = usuario;
        this.idLugar = idLugar;
        this.idTerminal = idTerminal;       
        
        unidadProductoDAO = new UnidadProductoDAOImlp(connectionDB);
        unidadMedidaDAO = new UnidadMedidaDAOImpl(connectionDB);
        productoDAO = new ProductoDAOImpl(connectionDB);
        transaccionDAO = new TransaccionDAOImpl(connectionDB);
        detalleTransaccionDAO = new DetalleTransaccionDAOImpl(connectionDB);
        
        vaciarComponentes();        
        llenarComboProductos();        
    }

    public void vaciarComponentes(){
        jcUnidadMedidaInicio.removeAllItems();
        jcUnidadMedidaFinal.removeAllItems();
    }
    
    public void limpiarComponentes(){
        jcUnidadMedidaFinal.setSelectedIndex(0);
        jcUnidadMedidaInicio.setSelectedIndex(0);
        jtxtCantidadFinal.setText("");
        jtxtCantidadInicial.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbDesempacar = new javax.swing.JButton();
        jlTituloFormulario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcUnidadMedidaInicio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcUnidadMedidaFinal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxtCantidadInicial = new javax.swing.JTextField();
        jtxtCantidadFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlStockProducto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jcProducto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProductoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Producto");

        jbDesempacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jbDesempacar.setText("Desempacar");
        jbDesempacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesempacarActionPerformed(evt);
            }
        });

        jlTituloFormulario.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloFormulario.setText("Desempaque");
        jlTituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcUnidadMedidaInicio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcUnidadMedidaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcUnidadMedidaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcUnidadMedidaInicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Unidad Medida 2");

        jcUnidadMedidaFinal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcUnidadMedidaFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcUnidadMedidaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcUnidadMedidaFinalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Cantidad 1");

        jtxtCantidadInicial.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtxtCantidadInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtxtCantidadFinal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtxtCantidadFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Cantidad 2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Unidad Medida 1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Stock:");

        jlStockProducto.setForeground(new java.awt.Color(153, 0, 51));
        jlStockProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlStockProducto.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcUnidadMedidaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlStockProducto))
                    .addComponent(jtxtCantidadInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtxtCantidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcUnidadMedidaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcUnidadMedidaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jlStockProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCantidadInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcUnidadMedidaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCantidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTituloFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jbDesempacar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlTituloFormulario)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbDesempacar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcUnidadMedidaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcUnidadMedidaInicioActionPerformed
        seleccionarUnidadInicio();
    }//GEN-LAST:event_jcUnidadMedidaInicioActionPerformed

    private void jcUnidadMedidaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcUnidadMedidaFinalActionPerformed
        seleccionarUnidadFinal();
    }//GEN-LAST:event_jcUnidadMedidaFinalActionPerformed

    private void jcProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProductoActionPerformed
        seleccionarProducto();
    }//GEN-LAST:event_jcProductoActionPerformed

    private void jbDesempacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesempacarActionPerformed
        boolean aux = true;
        
        if(idUnidadMedida2 == 0){
            JOptionPane.showMessageDialog( null, "Registrar las unidades del prodcuto!!!" , "Error", JOptionPane.ERROR_MESSAGE);
            aux = false;
        }
        
        if(jtxtCantidadInicial.getText().trim().length() == 0){
            JOptionPane.showMessageDialog( null, "Registrar cantidad producto a desempacar!!!" , "Error", JOptionPane.ERROR_MESSAGE);
            jtxtCantidadInicial.requestFocus();
            aux = false;
        }
        
        if(jtxtCantidadFinal.getText().trim().length() == 0){
            JOptionPane.showMessageDialog( null, "Registrar cantidad desempaque!!!" , "Error", JOptionPane.ERROR_MESSAGE);
            jtxtCantidadFinal.requestFocus();
            aux = false;
        }
        
        if(idUnidadMedida2 == idUnidadMedida1){
            JOptionPane.showMessageDialog( null, "Las unidades deben ser diferente!!!" , "Error", JOptionPane.ERROR_MESSAGE);
            aux = false;
        }
        
        if(aux){
            jbDesempacar.setEnabled(false);
            desempacar();
            jbDesempacar.setEnabled(true);
            limpiarComponentes();
        }
        
    }//GEN-LAST:event_jbDesempacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDesempaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDesempaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDesempaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDesempaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDesempaque().setVisible(true);
            }
        });
    }
    
    public void llenarComboProductos(){
        
        String sel = "Sel";
        
        jcProducto.removeAllItems();
        jcProducto.addItem(sel);
        HashMap<String, Integer> map = productoDAO.getProductoClaveValor();

        for (String s : map.keySet()) {
            jcProducto.addItem(s.toString());
        }
    }
    
    public void llenarComboUnidadMedidaInicio(int idProducto) {
        String sel = "Sel";

        jcUnidadMedidaInicio.removeAllItems();
        jcUnidadMedidaInicio.addItem(sel);

        HashMap<String, Integer> map = unidadMedidaDAO.unidadMedidaClaveValorProducto(idProducto);

        for (String s : map.keySet()) {
            jcUnidadMedidaInicio.addItem(s.toString());
        }
    }
    
    public void llenarComboUnidadMedidaFinal(int idProducto) {
        String sel = "Sel";

        jcUnidadMedidaFinal.removeAllItems();
        jcUnidadMedidaFinal.addItem(sel);

        HashMap<String, Integer> map = unidadMedidaDAO.unidadMedidaClaveValorProducto(idProducto);

        for (String s : map.keySet()) {
            jcUnidadMedidaFinal.addItem(s.toString());
        }
    }
    
    private void seleccionarProducto(){
        String sel = null;        
        String comp = "Sel";
        HashMap<String, Integer> map = productoDAO.getProductoClaveValor();
            
        try {
            sel = jcProducto.getSelectedItem().toString();

//            System.out.println("elemento seleccionado "+ sel);

            if(sel.equals(comp)){
                idProducto = 0;
            }
            else{
                idProducto = Integer.valueOf(map.get(sel).toString());
                llenarComboUnidadMedidaInicio(idProducto);
                llenarComboUnidadMedidaFinal(idProducto);
            }
        } catch (Exception e) {
        }
    }
    
    private void seleccionarUnidadInicio(){        
        String sel = null;        
        String comp = "Sel";        
        HashMap<String, Integer> map = unidadMedidaDAO.unidadMedidaClaveValor();
            
        try {
            sel = jcUnidadMedidaInicio.getSelectedItem().toString();

            if(sel.equals(comp)){
                idUnidadMedida1 = 0;
            }
            else{
                idUnidadMedida1 = Integer.valueOf(map.get(sel).toString());
                
                jlStockProducto.setText(String.valueOf(
                    unidadProductoDAO.getStockProducto(idProducto, idUnidadMedida1, idLugar)));
                idUnidadMedida2 = 0;
            }
        } catch (Exception e) {
        }
    }
    
    private void seleccionarUnidadFinal(){
        String sel = null;
        String comp = "Sel";
        HashMap<String, Integer> map = unidadMedidaDAO.unidadMedidaClaveValor();            
        try {
            sel = jcUnidadMedidaFinal.getSelectedItem().toString();

            if(sel.equals(comp)){
                idUnidadMedida2 = 0;
            }
            else{
                idUnidadMedida2 = Integer.valueOf(map.get(sel).toString());                
            }
        } catch (Exception e) {
        }
    }
    
    public void desempacar(){
        int cantidadInicial;
        int cantidadFinal;
        
        int idTipoTransaccion = 0;
        int idTransaccion = 0;
        int idEntregaTransaccionDesempaque = 0;
        int idEntregaTransaccionDesembalaje = 0;
        
        cantidadInicial = Integer.valueOf(jtxtCantidadInicial.getText().toString().trim());
        cantidadFinal = Integer.valueOf(jtxtCantidadFinal.getText().toString().trim());
        
        idTipoTransaccion = 9; // registro transaccion
        idTransaccion = resgistrarTransaccion(idTipoTransaccion);        
        registrarDetalleTransaccion(idTransaccion, idProducto, idUnidadMedida1, cantidadInicial);
        
        idTipoTransaccion = 8; // entrega
        idEntregaTransaccionDesempaque = resgistrarTransaccion(idTipoTransaccion);
        registrarDetalleTransaccion(idEntregaTransaccionDesempaque, idProducto, idUnidadMedida1, cantidadInicial);
        registrarEntregaTransaccion(idEntregaTransaccionDesempaque, idTransaccion);
        
        idTipoTransaccion = 7; // recepcion
        idEntregaTransaccionDesembalaje = resgistrarTransaccion(idTipoTransaccion);
        registrarDetalleTransaccion(idEntregaTransaccionDesembalaje, idProducto, idUnidadMedida2, cantidadFinal);
        registrarEntregaTransaccion(idEntregaTransaccionDesembalaje, idTransaccion);
        
        JOptionPane.showMessageDialog( null, "Desempaque concluido, revisar Stock!!!" , "Advertencia", JOptionPane.WARNING_MESSAGE);
        
    }
    
    public int resgistrarTransaccion(int idTipoTransaccion){
        int nroTipoTransaccion = 0;
        int tipoMovimineto = transaccionDAO.getTipoMovimiento(idTipoTransaccion);

        int idTransaccion = 0;
        String estado = "A";
        String descripcion = "";
        int idClienteProveedor = 0;

        java.util.Date hoy = new java.util.Date();
        java.sql.Date fecha = new java.sql.Date(hoy.getTime());

        nroTipoTransaccion = transaccionDAO.getNroTipoTransaccion(idTipoTransaccion);

        descripcion = "Desempaque - Embalaje";

        Transaccion trans = new Transaccion(fecha, idTipoTransaccion, nroTipoTransaccion,
                idLugar, idTerminal, tipoMovimineto, 
                estado, usuario, descripcion, idClienteProveedor);

        idTransaccion = transaccionDAO.insertarTransaccion(trans);

        return idTransaccion;       
    }
    
    public void registrarDetalleTransaccion(int idTransaccion, int idProd, int idUnidadMedida, int cantidad) {

        double valorUnitario = 0;
        double valorTotal = 0;
        String tipoValor = "N";

        ArrayList<DetalleTransaccion> detTrans = new ArrayList<DetalleTransaccion>();

        DetalleTransaccion dt = new DetalleTransaccion();

        dt.setIdTransaccion(idTransaccion);
        dt.setIdProducto(idProd);
        dt.setIdUnidadMedida(idUnidadMedida);
        dt.setCantidad(cantidad);
        dt.setValorUnitario(valorUnitario);
        dt.setValorTotal(valorTotal);
        dt.setTipoValor(tipoValor);

        detTrans.add(dt);

        detalleTransaccionDAO.insertarDetalleTransaccion(detTrans);
    }

    public void registrarEntregaTransaccion(int idEntregaTransaccion, int idTransaccion) {        
        transaccionDAO.insertarEntregaTransaccion(idTransaccion, idEntregaTransaccion);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbDesempacar;
    private javax.swing.JComboBox<String> jcProducto;
    private javax.swing.JComboBox<String> jcUnidadMedidaFinal;
    private javax.swing.JComboBox<String> jcUnidadMedidaInicio;
    private javax.swing.JLabel jlStockProducto;
    private javax.swing.JLabel jlTituloFormulario;
    private javax.swing.JTextField jtxtCantidadFinal;
    private javax.swing.JTextField jtxtCantidadInicial;
    // End of variables declaration//GEN-END:variables
}
