/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.vistas.configuracion.FormConfiguraciones;
import almacenes.vistas.configuracion.FormDosificacion;
import almacenes.vistas.configuracion.FormLugar;
import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.Configuracion;
import almacenes.model.Permiso;
import almacenes.vistas.configuracion.FormSucursal;
import almacenes.vistas.configuracion.FormTerminal;
import dao.FacturaDAO;
import dao.FacturaDAOImpl;
import dao.SistemaDAO;
import dao.SistemaDAOImpl;
import dao.SucursalDAO;
import dao.SucursalDAOImpl;
import dao.TerminalDAO;
import dao.TerminalDAOImpl;
import java.awt.AWTException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author georgeguitar
 */
public class FormMenu extends javax.swing.JFrame {
    private DatabaseUtils databaseUtils;
    private Connection connectionDB;
    private String idUsuario;
    private String hostName;
    SistemaDAO sistemaDAO;
    private byte idTerminal;
    private byte idLugar;
    
    private static final boolean config = true; // cuando la configuracion ha sido correcta
    private static final String MENU_PROCESOS = "menu_procesos";
    private static final String MENU_VENTAS = "menu_ventas";
    private static final String MENU_COMPRAS = "menu_compras";
    private static final String CAJA_INICIAL = "caja_inicial";
    private static final String CERRAR_CAJA = "cerrar_caja";
        
    private static final String MENU_CONFIGURACION = "menu_configuracion";
    private static final String MENU_CONFIGURACION_MARCAS = "menu_configuracion_marcas";
    private static final String MENU_CONFIGURACION_PROCEDENCIA = "menu_configuracion_procedencia";
    private static final String MENU_CONFIGURACION_RUBROS = "menu_configuracion_rubros";
    private static final String MENU_CONFIGURACION_UNIDAD_MEDIDA = "menu_configuracion_unidad_medida";
    private static final String MENU_CONFIGURACION_PRODUCTOS = "menu_configuracion_productos";
    
    private static final String MENU_ADMINISTRACION = "menu_administracion";
    
    private static final String MENU_INFORMES = "menu_informes";
    //private static final String MENU_PROCESOS_VENTAS = "menu_procesos_ventas";
    
    
    
    private static final int REPORTE_UNO = 1;
    private static final int REPORTE_DOS = 2;
    private static final int REPORTE_TRES = 3;
    private static final int REPORTE_CUATRO = 4;
    
    private SucursalDAO sucursalDAO;
    private FacturaDAO facturaDAO;
    
    /**
     * Creates new form Menu
     */
    public FormMenu() {
        initComponents();
    }

    public FormMenu(Connection _connectionDB, String _idUsuario, byte idLugar, byte idTerminal) {
        initComponents();
        this.databaseUtils = new DatabaseUtils();
        this.connectionDB = _connectionDB;
        sistemaDAO = new SistemaDAOImpl(connectionDB);
        sucursalDAO = new SucursalDAOImpl(connectionDB);
        facturaDAO = new FacturaDAOImpl(_connectionDB);
        this.idUsuario = _idUsuario;
        this.idLugar = idLugar;
        this.idTerminal = idTerminal;
        ocultarMenus();
        habilitarMenusUsuario();
        jMenuRestaurarDB.setVisible(false);
        
        datosTerminal();
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jlTerminal = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuFacturaFacil = new javax.swing.JMenuItem();
        jMenuListasFacturaFacil = new javax.swing.JMenuItem();
        jMenuProcesos = new javax.swing.JMenu();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuVentas = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuCompras = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmenuCajaInicial = new javax.swing.JMenuItem();
        jmenuCerrarCaja = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmAnularTrans = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmenuReimpresion = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jmenuDesempaque = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jmlistaTrnasacciones = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jmenuCotizacion = new javax.swing.JMenuItem();
        jMenuCotizacionesPendientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuEntregasChange = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmenuPendientesCobro = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jmenuIngresos = new javax.swing.JMenuItem();
        jmenuEgresos = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuLaboratorio = new javax.swing.JMenuItem();
        jMenuFamilia = new javax.swing.JMenuItem();
        jMenuRubros = new javax.swing.JMenuItem();
        jMenuUnidadMedida = new javax.swing.JMenuItem();
        jMenuProductos = new javax.swing.JMenuItem();
        jmenuCliente = new javax.swing.JMenuItem();
        jmenuProveedor = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuILugar = new javax.swing.JMenuItem();
        jMenuTerminal = new javax.swing.JMenuItem();
        jMenuSucursal = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuStockInicial = new javax.swing.JMenuItem();
        jmenuUsers = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmenuDosificacion = new javax.swing.JMenuItem();
        jmenuCodigoControl = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuBackupDB = new javax.swing.JMenuItem();
        jMenuRestaurarDB = new javax.swing.JMenuItem();
        jMenuConfiguraciones = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuStockProductos = new javax.swing.JMenuItem();
        jmenuMovimientoCajaGeneral = new javax.swing.JMenuItem();
        jmenuEntregas = new javax.swing.JMenuItem();
        jmenuLibroVentas = new javax.swing.JMenuItem();
        jmenuArqueos = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlUsuario.setText("Usuario");

        jlTerminal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTerminal.setText("Terminal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsuario)
                    .addComponent(jlTerminal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jButton1.setToolTipText("Salir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        jButton2.setToolTipText("Ventas");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jMenuArchivo.setText("Archivo");
        jMenuArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem1);

        jMenuBar1.add(jMenuArchivo);

        jMenu1.setText("Factura Facil");
        jMenu1.setEnabled(false);
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuFacturaFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura_facil.png"))); // NOI18N
        jMenuFacturaFacil.setText("Factura Facil");
        jMenuFacturaFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFacturaFacilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFacturaFacil);

        jMenuListasFacturaFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listas.jpg"))); // NOI18N
        jMenuListasFacturaFacil.setText("Listas");
        jMenuListasFacturaFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListasFacturaFacilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuListasFacturaFacil);

        jMenuBar1.add(jMenu1);

        jMenuProcesos.setText("Procesos");
        jMenuProcesos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuProcesos.add(jSeparator8);

        jMenuVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        jMenuVentas.setText("Ventas");
        jMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVentasActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuVentas);
        jMenuProcesos.add(jSeparator4);

        jMenuCompras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        jMenuCompras.setText("Compras");
        jMenuCompras.setName(""); // NOI18N
        jMenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComprasActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuCompras);
        jMenuProcesos.add(jSeparator2);

        jmenuCajaInicial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuCajaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja_inicial.png"))); // NOI18N
        jmenuCajaInicial.setText("Caja Inicial");
        jmenuCajaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCajaInicialActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuCajaInicial);

        jmenuCerrarCaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuCerrarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrar_caja.png"))); // NOI18N
        jmenuCerrarCaja.setText("Cerrar Caja");
        jmenuCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCerrarCajaActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuCerrarCaja);
        jMenuProcesos.add(jSeparator3);

        jmAnularTrans.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmAnularTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jmAnularTrans.setText("Anular Trans");
        jmAnularTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAnularTransActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmAnularTrans);
        jMenuProcesos.add(jSeparator5);

        jmenuReimpresion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuReimpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reimprimir.png"))); // NOI18N
        jmenuReimpresion.setText("Re Impresion");
        jmenuReimpresion.setEnabled(false);
        jmenuReimpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuReimpresionActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuReimpresion);
        jMenuProcesos.add(jSeparator9);

        jmenuDesempaque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuDesempaque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desempacar.png"))); // NOI18N
        jmenuDesempaque.setText("Desempaque");
        jmenuDesempaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuDesempaqueActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuDesempaque);
        jMenuProcesos.add(jSeparator14);

        jmlistaTrnasacciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmlistaTrnasacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listas.jpg"))); // NOI18N
        jmlistaTrnasacciones.setText("Lista Transacciones");
        jmlistaTrnasacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlistaTrnasaccionesActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmlistaTrnasacciones);
        jMenuProcesos.add(jSeparator10);

        jmenuCotizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calculadora.jpg"))); // NOI18N
        jmenuCotizacion.setText("Cotizacion");
        jmenuCotizacion.setEnabled(false);
        jmenuCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCotizacionActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmenuCotizacion);

        jMenuCotizacionesPendientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuCotizacionesPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cotiizacion_pendiente.png"))); // NOI18N
        jMenuCotizacionesPendientes.setText("Cotizaciones Pendientes");
        jMenuCotizacionesPendientes.setEnabled(false);
        jMenuCotizacionesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCotizacionesPendientesActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuCotizacionesPendientes);

        jMenuBar1.add(jMenuProcesos);

        jMenu2.setText("Creditos");
        jMenu2.setEnabled(false);
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuEntregasChange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuEntregasChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Entregas-Credito.png"))); // NOI18N
        jMenuEntregasChange.setText("Pedidos");
        jMenuEntregasChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEntregasChangeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuEntregasChange);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/credito.png"))); // NOI18N
        jMenuItem3.setText("Credito Ventas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jmenuPendientesCobro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuPendientesCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago_transaccion.png"))); // NOI18N
        jmenuPendientesCobro.setText("Pendientes Cobro");
        jmenuPendientesCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuPendientesCobroActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuPendientesCobro);
        jMenu2.add(jSeparator11);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EntregaPendiente.png"))); // NOI18N
        jMenuItem4.setText("Entregas Pendientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator12);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tax.png"))); // NOI18N
        jMenuItem5.setText("Credito X Facturar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator13);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Otros");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmenuIngresos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingreso.png"))); // NOI18N
        jmenuIngresos.setText("Ingresos");
        jmenuIngresos.setEnabled(false);
        jmenuIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuIngresosActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuIngresos);

        jmenuEgresos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        jmenuEgresos.setText("Egresos");
        jmenuEgresos.setEnabled(false);
        jmenuEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEgresosActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuEgresos);

        jMenuBar1.add(jMenu3);

        jMenuConfiguracion.setText("Configuración");
        jMenuConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuLaboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marca.png"))); // NOI18N
        jMenuLaboratorio.setText("Laboratorio");
        jMenuLaboratorio.setName(""); // NOI18N
        jMenuLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaboratorioActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuLaboratorio);

        jMenuFamilia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/procedencia.png"))); // NOI18N
        jMenuFamilia.setText("Familia");
        jMenuFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFamiliaActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuFamilia);

        jMenuRubros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuRubros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rubro.png"))); // NOI18N
        jMenuRubros.setText("Rubros");
        jMenuRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRubrosActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuRubros);

        jMenuUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuUnidadMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidadMedida.png"))); // NOI18N
        jMenuUnidadMedida.setText("Unidad Medida");
        jMenuUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUnidadMedidaActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuUnidadMedida);

        jMenuProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos.png"))); // NOI18N
        jMenuProductos.setText("Productos");
        jMenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductosActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuProductos);

        jmenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clients.png"))); // NOI18N
        jmenuCliente.setText("Clientes");
        jmenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuClienteActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jmenuCliente);

        jmenuProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kuser.png"))); // NOI18N
        jmenuProveedor.setText("Proveedores");
        jmenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProveedorActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jmenuProveedor);
        jMenuConfiguracion.add(jSeparator7);

        jMenuILugar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuILugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lugar.png"))); // NOI18N
        jMenuILugar.setText("Lugar");
        jMenuILugar.setEnabled(false);
        jMenuILugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuILugarActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuILugar);

        jMenuTerminal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/terminal.png"))); // NOI18N
        jMenuTerminal.setText("Terminal");
        jMenuTerminal.setEnabled(false);
        jMenuTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTerminalActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuTerminal);

        jMenuSucursal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sucursal.png"))); // NOI18N
        jMenuSucursal.setText("Sucursal");
        jMenuSucursal.setEnabled(false);
        jMenuSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSucursalActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuSucursal);

        jMenuBar1.add(jMenuConfiguracion);

        jMenuAdministracion.setText("Administración");
        jMenuAdministracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuStockInicial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuStockInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configurar.png"))); // NOI18N
        jMenuStockInicial.setText("Ajuste Stock");
        jMenuStockInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStockInicialActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuStockInicial);

        jmenuUsers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add-user-icon.png"))); // NOI18N
        jmenuUsers.setText("Usuarios");
        jmenuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuUsersActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuUsers);
        jMenuAdministracion.add(jSeparator6);

        jmenuDosificacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuDosificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder-add-icon.png"))); // NOI18N
        jmenuDosificacion.setText("Dosificacion");
        jmenuDosificacion.setEnabled(false);
        jmenuDosificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuDosificacionActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuDosificacion);

        jmenuCodigoControl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuCodigoControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigo_control.png"))); // NOI18N
        jmenuCodigoControl.setText("Codigo Control Impuestos");
        jmenuCodigoControl.setEnabled(false);
        jmenuCodigoControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCodigoControlActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jmenuCodigoControl);
        jMenuAdministracion.add(jSeparator1);

        jMenuBackupDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBackupDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backup.png"))); // NOI18N
        jMenuBackupDB.setText("Backup DB");
        jMenuBackupDB.setEnabled(false);
        jMenuBackupDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBackupDBActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuBackupDB);

        jMenuRestaurarDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuRestaurarDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/restore_db.png"))); // NOI18N
        jMenuRestaurarDB.setText("Restaurar DB");
        jMenuRestaurarDB.setEnabled(false);
        jMenuRestaurarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRestaurarDBActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuRestaurarDB);

        jMenuConfiguraciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/setup.png"))); // NOI18N
        jMenuConfiguraciones.setText("Configuraciones");
        jMenuConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfiguracionesActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuConfiguraciones);

        jMenuBar1.add(jMenuAdministracion);

        jMenuInformes.setText("Informes");
        jMenuInformes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuStockProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuStockProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock.png"))); // NOI18N
        jMenuStockProductos.setText("Stock Productos");
        jMenuStockProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStockProductosActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuStockProductos);

        jmenuMovimientoCajaGeneral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuMovimientoCajaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movimiento_caja.png"))); // NOI18N
        jmenuMovimientoCajaGeneral.setText("Movimiento Caja General");
        jmenuMovimientoCajaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuMovimientoCajaGeneralActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuMovimientoCajaGeneral);

        jmenuEntregas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entregas.png"))); // NOI18N
        jmenuEntregas.setText("Reporte Entregas");
        jmenuEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEntregasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuEntregas);

        jmenuLibroVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuLibroVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        jmenuLibroVentas.setText("Libro Ventas");
        jmenuLibroVentas.setEnabled(false);
        jmenuLibroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuLibroVentasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuLibroVentas);

        jmenuArqueos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmenuArqueos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arqueos.png"))); // NOI18N
        jmenuArqueos.setText("Lista Arqueos");
        jmenuArqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuArqueosActionPerformed(evt);
            }
        });
        jMenuInformes.add(jmenuArqueos);

        jMenuBar1.add(jMenuInformes);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        salir();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVentasActionPerformed
        int idTipoTransaccion = 2;
        int idTipoTransaccionEntrega = 8;
        int idTransaccionCotizacion = 0;
       
        byte idSucursal = sucursalDAO.getIdSucursal(idLugar);
        /*
        if(!facturaDAO.getEstadoDosificacion(idSucursal)){
            JOptionPane.showMessageDialog( null, "¡No se cuenta con una dosificación válida, no podrá emitir facturas!!!" , "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(!facturaDAO.getFechaLimiteEmisionVigente(idSucursal)){
               JOptionPane.showMessageDialog( null, "¡La fecha de emisión para las facturas ha vencido, no podrá emitir facturas!!!" , "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        */
        
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                            idTipoTransaccion, idTipoTransaccionEntrega, 
                                            idUsuario, idLugar, idTerminal);

        formTrans.setVisible(true);
    }//GEN-LAST:event_jMenuVentasActionPerformed

    private void jMenuRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRubrosActionPerformed
        FormRubro frubro = new FormRubro(connectionDB);
        frubro.setVisible(true);
    }//GEN-LAST:event_jMenuRubrosActionPerformed

    private void jMenuUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUnidadMedidaActionPerformed
        FormUnidadMedida fUmed = new FormUnidadMedida(connectionDB);
        fUmed.setVisible(true);
    }//GEN-LAST:event_jMenuUnidadMedidaActionPerformed

    private void jMenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductosActionPerformed
        FormProducto fprod = new FormProducto(connectionDB, idUsuario, idLugar);
        fprod.setVisible(true);
    }//GEN-LAST:event_jMenuProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salir();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComprasActionPerformed
        int idTipoTransaccion = 1;// nro para compras
        int idTipoTransaccionEntrega = 7;
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                        idTipoTransaccion, idTipoTransaccionEntrega, 
                                        idUsuario, idLugar, idTerminal);
        formTrans.setVisible(true);
    }//GEN-LAST:event_jMenuComprasActionPerformed

    private void jMenuStockInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStockInicialActionPerformed
//        int idTipoTransaccion = 6;// stock inicial
//        int idTipoTransaccionEntrega = 7;
//        FormTransaccionCompras formTrans = new FormTransaccionCompras(connectionDB, 
//                                        idTipoTransaccion, idTipoTransaccionEntrega, 
//                                        idUsuario, idLugar, idTerminal);
//        formTrans.setVisible(true);



        int idTipoTransaccion = 6;// ajuste stock 
        int idTipoTransaccionEntrega = 7;
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                        idTipoTransaccion, idTipoTransaccionEntrega, 
                                        idUsuario, idLugar, idTerminal);
        formTrans.setVisible(true);
        /*
        FormAjusteStock formAjuste = new FormAjusteStock(connectionDB, idTipoTransaccion, 
                idTipoTransaccionEntrega, idUsuario, idLugar, idTerminal);
        formAjuste.setVisible(true);
        */
    }//GEN-LAST:event_jMenuStockInicialActionPerformed

    private void jMenuStockProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStockProductosActionPerformed
        FormStockProducto fStock = new FormStockProducto(connectionDB);
        fStock.setVisible(true);
    }//GEN-LAST:event_jMenuStockProductosActionPerformed

    private void jmenuCajaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCajaInicialActionPerformed
        FormCajaInicial fcajaIn = new FormCajaInicial(connectionDB, idUsuario, idLugar, idTerminal);
        fcajaIn.setVisible(true);
    }//GEN-LAST:event_jmenuCajaInicialActionPerformed

    private void jmenuCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCerrarCajaActionPerformed
        FormArqueoCaja formArq = new FormArqueoCaja(connectionDB, idUsuario, idLugar, idTerminal);
        formArq.setVisible(true);
                
    }//GEN-LAST:event_jmenuCerrarCajaActionPerformed

    private void jmenuEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEntregasActionPerformed
        new ElegirFechasImprimirReportes(this, false, connectionDB, idUsuario, REPORTE_DOS).setVisible(true);
    }//GEN-LAST:event_jmenuEntregasActionPerformed

    private void jmAnularTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAnularTransActionPerformed
        FormAnularTransaccion fAnular = new FormAnularTransaccion(connectionDB, idUsuario);
        fAnular.setVisible(true);
    }//GEN-LAST:event_jmAnularTransActionPerformed

    private void jmenuIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuIngresosActionPerformed
        
        String tipoCuenta = "I";
        int idTipoTransaccion = 5;
        FormIngresosEgresos fie = new FormIngresosEgresos(connectionDB, tipoCuenta, 
                idLugar, idUsuario, idTipoTransaccion, idTerminal);
        fie.setVisible(true);
        
    }//GEN-LAST:event_jmenuIngresosActionPerformed

    private void jmenuEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEgresosActionPerformed
        
        String tipoCuenta = "E";
        int idTipoTransaccion = 4;
        FormIngresosEgresos fie = new FormIngresosEgresos(connectionDB, tipoCuenta, 
                idLugar, idUsuario, idTipoTransaccion, idTerminal);
        fie.setVisible(true);
        
    }//GEN-LAST:event_jmenuEgresosActionPerformed

    private void jMenuBackupDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBackupDBActionPerformed
        try {
            Configuracion configuracion = sistemaDAO.getGestionConfiguraciones();
            if (configuracion.getRutaProgramasPG() == null) {
                JOptionPane.showMessageDialog( null, "¡No existe la ruta del programa para hacer backup! \n\n" + 
                        "¡Vaya al menu de configurarión para definir una ruta!" , "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                new FormBackupDB(connectionDB, idUsuario).setVisible(true);             
            }
        } catch (Exception ex){
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_jMenuBackupDBActionPerformed

    private void jMenuRestaurarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRestaurarDBActionPerformed
        new FormRestaurarDB(connectionDB, idUsuario).setVisible(true);
    }//GEN-LAST:event_jMenuRestaurarDBActionPerformed

    private void jMenuConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfiguracionesActionPerformed
        try {
            new FormConfiguraciones(connectionDB, idUsuario).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuConfiguracionesActionPerformed

    private void jmenuLibroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuLibroVentasActionPerformed
        FormLibroVentas fLibroVentas = new FormLibroVentas(connectionDB, idUsuario);
        fLibroVentas.setVisible(true);
    }//GEN-LAST:event_jmenuLibroVentasActionPerformed

    private void jmenuArqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuArqueosActionPerformed
        FormArqueos fArq = new FormArqueos(connectionDB);
        fArq.setVisible(true);
    }//GEN-LAST:event_jmenuArqueosActionPerformed

    private void jmenuMovimientoCajaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuMovimientoCajaGeneralActionPerformed
        new ElegirFechasImprimirReportes(this, false, connectionDB, idUsuario, REPORTE_CUATRO).setVisible(true);
    }//GEN-LAST:event_jmenuMovimientoCajaGeneralActionPerformed

    private void jmenuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuUsersActionPerformed
        FormUsuario fus = new FormUsuario(connectionDB);
        fus.setVisible(true);
    }//GEN-LAST:event_jmenuUsersActionPerformed

    private void jmenuCodigoControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCodigoControlActionPerformed
        FormValidarCodigoCotrol cod = new FormValidarCodigoCotrol();
        cod.setVisible(true);
    }//GEN-LAST:event_jmenuCodigoControlActionPerformed

    private void jmenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuClienteActionPerformed
        String tipo = "C";
        FormClienteProveedor formcli = new FormClienteProveedor(connectionDB, tipo);
        formcli.setVisible(true);
    }//GEN-LAST:event_jmenuClienteActionPerformed

    private void jmenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProveedorActionPerformed
        String tipo = "P";
        FormClienteProveedor formcli = new FormClienteProveedor(connectionDB, tipo);
        formcli.setVisible(true);
    }//GEN-LAST:event_jmenuProveedorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmenuPendientesCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuPendientesCobroActionPerformed
        int idTipoTransaccion = 3;// pedidos
        FormPendientesPago pend = new FormPendientesPago(connectionDB, idTipoTransaccion, idUsuario,
                    idLugar, idTerminal);
        pend.setVisible(true);
    }//GEN-LAST:event_jmenuPendientesCobroActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormFacturaCredito ffc = new FormFacturaCredito(connectionDB, idLugar);
        ffc.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int idTipoTransaccion = 2;
        int idTipoTransaccionEntrega = 8;
        FormTransaccion formTrans = new FormTransaccion(connectionDB, 
                                            idTipoTransaccion, idTipoTransaccionEntrega, 
                                            idUsuario, idLugar, idTerminal);
        formTrans.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jmenuReimpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuReimpresionActionPerformed
        FormReImpresionFactura reimp = new FormReImpresionFactura(connectionDB, idUsuario);
        reimp.setVisible(true);
    }//GEN-LAST:event_jmenuReimpresionActionPerformed

    private void jmenuDosificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuDosificacionActionPerformed
        FormDosificacion dos = new FormDosificacion(connectionDB);
        dos.setVisible(true);

    }//GEN-LAST:event_jmenuDosificacionActionPerformed

    private void jMenuILugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuILugarActionPerformed
        FormLugar l = new FormLugar(connectionDB, config);
        l.setVisible(true);
    }//GEN-LAST:event_jMenuILugarActionPerformed

    private void jMenuTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTerminalActionPerformed
        FormTerminal formTerminal = new FormTerminal(connectionDB, config);
        formTerminal.setVisible(true);
    }//GEN-LAST:event_jMenuTerminalActionPerformed

    private void jMenuSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSucursalActionPerformed
        FormSucursal formSucursal = new FormSucursal(connectionDB);
        formSucursal.setVisible(true);
    }//GEN-LAST:event_jMenuSucursalActionPerformed

    private void jMenuFacturaFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFacturaFacilActionPerformed
        FormFacturaFacil facturaFacil = new FormFacturaFacil(connectionDB, idLugar, config, idUsuario);
        facturaFacil.setVisible(true);
    }//GEN-LAST:event_jMenuFacturaFacilActionPerformed

    private void jmenuDesempaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuDesempaqueActionPerformed
        FormDesempaque desempaque = new FormDesempaque(connectionDB, idUsuario,
                    idLugar, idTerminal);
        desempaque.setVisible(true);
    }//GEN-LAST:event_jmenuDesempaqueActionPerformed

    private void jmlistaTrnasaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlistaTrnasaccionesActionPerformed
        FormListaTransacciones flt;
        try {
            flt = new FormListaTransacciones(connectionDB, idUsuario);
            flt.setVisible(true);
        } catch (AWTException ex) {
            Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmlistaTrnasaccionesActionPerformed

    private void jMenuListasFacturaFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListasFacturaFacilActionPerformed
        FormListaFacil listaFacil = new FormListaFacil(connectionDB);
        listaFacil.setVisible(true);
    }//GEN-LAST:event_jMenuListasFacturaFacilActionPerformed

    private void jMenuEntregasChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEntregasChangeActionPerformed
        int idTipoTransaccion = 3; //pedidos
        int idTransaccionCotizacion = 0;
        
        FormTransaccionPedidos credito = new FormTransaccionPedidos(connectionDB, 
                                            idTipoTransaccion, 
                                            idUsuario, idLugar, idTerminal, 
                                            idTransaccionCotizacion);
        credito.setVisible(true);
    }//GEN-LAST:event_jMenuEntregasChangeActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int idTipoTransaccionEntrega = 8;
        
        FormEntregasPendientes formPendientes = new FormEntregasPendientes(connectionDB, 
                                            idTipoTransaccionEntrega, 
                                            idLugar, idTerminal, idUsuario);
        formPendientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jmenuCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCotizacionActionPerformed
        int idTipoTransaccion = 10; //cotizacion
        
        FormCotizacion cotizacion = new FormCotizacion(connectionDB, 
                                            idTipoTransaccion, 
                                            idUsuario, idLugar, idTerminal);
        cotizacion.setVisible(true);
    }//GEN-LAST:event_jmenuCotizacionActionPerformed

    private void jMenuCotizacionesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCotizacionesPendientesActionPerformed
        FormListaCotizaciones flc = new FormListaCotizaciones(connectionDB, idUsuario, idLugar, idTerminal);
        flc.setVisible(true);
    }//GEN-LAST:event_jMenuCotizacionesPendientesActionPerformed

    private void jMenuLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaboratorioActionPerformed
        FormLaboratorio flaboratorio = new FormLaboratorio(connectionDB);
        flaboratorio.setVisible(true);
    }//GEN-LAST:event_jMenuLaboratorioActionPerformed

    private void jMenuFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFamiliaActionPerformed
        FormFamilia ffamilia = new FormFamilia(connectionDB);
        ffamilia.setVisible(true);
    }//GEN-LAST:event_jMenuFamiliaActionPerformed

    private void salir() {
        this.databaseUtils.close(connectionDB);
        System.exit(0);
    }
    
    private void habilitarMenusUsuario() {
        List<Permiso> permisosUsuario = new ArrayList<Permiso>();
        permisosUsuario = sistemaDAO.getPermisosUsuario(this.idUsuario);
        for (Permiso permiso : permisosUsuario) {
            if (permiso.getNombrePermiso().equals(MENU_PROCESOS)) {
                jMenuProcesos.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION)) {
                jMenuConfiguracion.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_ADMINISTRACION)) {
                jMenuAdministracion.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_INFORMES)) {
                jMenuInformes.setVisible(true);
            }            
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_PROCEDENCIA)) {
                //jMenuProcedencia.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_RUBROS)) {
                jMenuRubros.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_UNIDAD_MEDIDA)) {
                jMenuUnidadMedida.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_CONFIGURACION_PRODUCTOS)) {
                jMenuProductos.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_COMPRAS)) {
                jMenuCompras.setVisible(true);
            }
            if (permiso.getNombrePermiso().equals(MENU_VENTAS)) {
                jMenuVentas.setVisible(true);
            }
        }
        
        jlUsuario.setText("Usuario: " + idUsuario);
    }
    
    private void ocultarMenus() {
        jMenuConfiguracion.setVisible(false);
        jMenuAdministracion.setVisible(false);
        jMenuInformes.setVisible(false);        
        //jMenuProcedencia.setVisible(false); 
        jMenuProcesos.setVisible(false);
        jMenuProductos.setVisible(false);
        jMenuRubros.setVisible(false);
        jMenuUnidadMedida.setVisible(false);
        jMenuVentas.setVisible(false);
        jMenuCompras.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuItem jMenuBackupDB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCompras;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenuItem jMenuConfiguraciones;
    private javax.swing.JMenuItem jMenuCotizacionesPendientes;
    private javax.swing.JMenuItem jMenuEntregasChange;
    private javax.swing.JMenuItem jMenuFacturaFacil;
    private javax.swing.JMenuItem jMenuFamilia;
    private javax.swing.JMenuItem jMenuILugar;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuLaboratorio;
    private javax.swing.JMenuItem jMenuListasFacturaFacil;
    private javax.swing.JMenu jMenuProcesos;
    private javax.swing.JMenuItem jMenuProductos;
    private javax.swing.JMenuItem jMenuRestaurarDB;
    private javax.swing.JMenuItem jMenuRubros;
    private javax.swing.JMenuItem jMenuStockInicial;
    private javax.swing.JMenuItem jMenuStockProductos;
    private javax.swing.JMenuItem jMenuSucursal;
    private javax.swing.JMenuItem jMenuTerminal;
    private javax.swing.JMenuItem jMenuUnidadMedida;
    private javax.swing.JMenuItem jMenuVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlTerminal;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenuItem jmAnularTrans;
    private javax.swing.JMenuItem jmenuArqueos;
    private javax.swing.JMenuItem jmenuCajaInicial;
    private javax.swing.JMenuItem jmenuCerrarCaja;
    private javax.swing.JMenuItem jmenuCliente;
    private javax.swing.JMenuItem jmenuCodigoControl;
    private javax.swing.JMenuItem jmenuCotizacion;
    private javax.swing.JMenuItem jmenuDesempaque;
    private javax.swing.JMenuItem jmenuDosificacion;
    private javax.swing.JMenuItem jmenuEgresos;
    private javax.swing.JMenuItem jmenuEntregas;
    private javax.swing.JMenuItem jmenuIngresos;
    private javax.swing.JMenuItem jmenuLibroVentas;
    private javax.swing.JMenuItem jmenuMovimientoCajaGeneral;
    private javax.swing.JMenuItem jmenuPendientesCobro;
    private javax.swing.JMenuItem jmenuProveedor;
    private javax.swing.JMenuItem jmenuReimpresion;
    private javax.swing.JMenuItem jmenuUsers;
    private javax.swing.JMenuItem jmlistaTrnasacciones;
    // End of variables declaration//GEN-END:variables

    private void datosTerminal() {
        TerminalDAO terminal = new TerminalDAOImpl(this.connectionDB);
        hostName = terminal.getNameHost();
//        idTerminal = terminal.getIdTerminal(hostName);
//        if (idTerminal == 0) {
//                JOptionPane.showMessageDialog( null, "El equipo no ha sido configurado correctamente \n\n" + 
//                        "¡consulte con el administrador!" , "Error", JOptionPane.ERROR_MESSAGE);
//                
//                this.databaseUtils.close(connectionDB);
//                System.exit(0);
//                
//            }
        jlTerminal.setText("Terminal: " + hostName);
    }
}
