/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacenes.vistas;

import almacenes.conectorDB.DatabaseUtils;
import almacenes.model.EntregaPendiente;
import almacenes.model.PendientePago;
import dao.EntregasDAO;
import dao.EntregasDAOImpl;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jcarlos.porcel
 */
public class FormEntregasPendientes extends javax.swing.JFrame {

    private DatabaseUtils databaseUtils;
    private Connection connectionDB, connectionTemp;
    private DefaultTableModel dtm;    
    private int idTipoTransaccionEntrega;  // tipo de entrega q se ejecutara
    private byte idLugar;
    private byte idTerminal;
    private String usuario;
    private DecimalFormat df;
    
    EntregasDAO entregasDAO;

    public FormEntregasPendientes(Connection connectionDB, 
            int idTipoTransaccionEntrega, byte idLugar, 
            byte idTerminal, String usuario) {
        this.connectionDB = connectionDB;        
        this.idTipoTransaccionEntrega = idTipoTransaccionEntrega;
        this.idLugar = idLugar;
        this.idTerminal = idTerminal;
        this.usuario = usuario;
//        headerTabla();
        iniciarVariables();
        llenarPendientesEntrega();
    }
    
    public void headerTabla() {
        Font f = new Font("Times New Roman", Font.BOLD, 13);

        jtPendientes.getTableHeader().setFont(f);
        jtPendientes.getTableHeader().setBackground(Color.orange);
    }
    
    private void iniciarVariables(){
        entregasDAO = new EntregasDAOImpl(connectionDB);
    }
    
    public void llenarPendientesEntrega(){
        
        ArrayList<EntregaPendiente> lista = new ArrayList<EntregaPendiente>();
        
        lista = entregasDAO.getListaEntregasPendientes();
        
        dtm = (DefaultTableModel) this.jtPendientes.getModel();
        dtm.setRowCount(0);
        
        jtPendientes.setModel(dtm);
        
        Object[] fila = new Object[6];
        
//        System.out.println("nro de registros en pila: " + r.size());
        
        for(int i=0; i< lista.size(); i++){
            fila[0] = lista.get(i).getIdTransaccionCredito();
            fila[1] = lista.get(i).getNroTipoTransaccion();
            fila[2] = lista.get(i).getFecha();
            fila[3] = lista.get(i).getNombreCompleto();
            fila[4] = lista.get(i).getDireccion();
            fila[5] = lista.get(i).getTelefonos();
            
            dtm.addRow(fila);
        }
        
        jtPendientes.setModel(dtm);
    }

    
    
    public FormEntregasPendientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPendientes = new javax.swing.JTable();
        jlTituloFormulario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idTransaccion", "Nro Trans.", "Fecha", "Nombre Cliente", "Direccion", "Telefonos"
            }
        ));
        jScrollPane1.setViewportView(jtPendientes);
        if (jtPendientes.getColumnModel().getColumnCount() > 0) {
            jtPendientes.getColumnModel().getColumn(0).setMinWidth(0);
            jtPendientes.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtPendientes.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jlTituloFormulario.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlTituloFormulario.setForeground(new java.awt.Color(153, 0, 51));
        jlTituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloFormulario.setText("Entregas Pendientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jlTituloFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(40, 40, 40)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jlTituloFormulario)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEntregasPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEntregasPendientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTituloFormulario;
    private javax.swing.JTable jtPendientes;
    // End of variables declaration//GEN-END:variables
}
